### PR TITLE
Add php8.0 support

### LINKED ISSUE #540: Support for PHP8 ?
Is it possible to add PHP8 support to this image so it can be used for testing/developing PHP8 compatibility of WordPress plugins and themes?

https://wiki.php.net/todo/php80

https://make.wordpress.org/core/2020/10/06/call-for-testing-php-8-0/

I use a docker environment based on this image and it would be great if I could build a variation of my dev env with PHP8 installed. 

Let me know I can help 😄

### PR DESCRIPTION
**Pull request by tianon**
Closes #540

(I don't think this makes sense to make the default just yet, but definitely makes sense to support as an optional variant!)

### CODE REVIEW

**Comment by LeoColomb** [comment]
Indeed, but https://github.com/Imagick/imagick/issues/358 is blocking for full support.

**Comment by spacedmonkey** [comment]
Possibility silly question. But WordPress supports both  Imagick and GD out of the box. Would it be possible for to use GD instead of  Imagick?

**Comment by tianon** [comment]
Great question!  Are _all_ the core functionality uses of `imagick` able to fall back to GD?  What are the pros/cons?  Is there one which is "officially" recommended/preferred over the other? :see_no_evil:

**Comment by onadrog** [comment]
> 
> 
> Possibility silly question. But WordPress supports both Imagick and GD out of the box. Would it be possible for to use GD instead of Imagick?

Hi you can compile imagick yourself, here is the link to the the Dockerfile I've created and using waiting the official image [https://github.com/onadrog/wordpress56-php8.0-fpm](url) it seems ok.

**Comment by mweichert** [comment]
How do I build the docker images from this repo?

**Comment by mweichert** [comment]
> How do I build the docker images from this repo?

Figured it out:
```
docker build ./php8.0/apache/ -t wordpress:5.6-apache-php8
```

**Comment by mweichert** [comment]
> Indeed, but [Imagick/imagick#358](https://github.com/Imagick/imagick/issues/358) is blocking for full support.

Note, you can get the image to build by altering the Dockerfile to build imagick from source instead of using pecl:
```
FROM php:8.0-apache

# persistent dependencies
RUN set -eux; \
	apt-get update; \
	apt-get install -y --no-install-recommends \
# Ghostscript is required for rendering PDF previews
		ghostscript \
	; \
	rm -rf /var/lib/apt/lists/*

# install the PHP extensions we need (https://make.wordpress.org/hosting/handbook/handbook/server-environment/#php-extensions)
RUN set -ex; \
	\
	savedAptMark="$(apt-mark showmanual)"; \
	\
	apt-get update; \
	apt-get install -y --no-install-recommends \
		libfreetype6-dev \
		libjpeg-dev \
		libmagickwand-dev \
		libpng-dev \
		libzip-dev \
		git \
	; \
	\
	docker-php-ext-configure gd --with-freetype --with-jpeg; \
	docker-php-ext-install -j "$(nproc)" \
		bcmath \
		exif \
		gd \
		mysqli \
		zip \
	; \
	git clone https://github.com/Imagick/imagick; \
	cd imagick; \
	phpize && ./configure; \
	make; \
	make install; \
	\
	docker-php-ext-enable imagick; \
	\
# reset apt-mark's "manual" list so that "purge --auto-remove" will remove all build dependencies
	apt-mark auto '.*' > /dev/null; \
	apt-mark manual $savedAptMark; \
	ldd "$(php -r 'echo ini_get("extension_dir");')"/*.so \
		| awk '/=>/ { print $3 }' \
		| sort -u \
		| xargs -r dpkg-query -S \
		| cut -d: -f1 \
		| sort -u \
		| xargs -rt apt-mark manual; \
	\
	apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \
	rm -rf /var/lib/apt/lists/*

# set recommended PHP.ini settings
# see https://secure.php.net/manual/en/opcache.installation.php
RUN set -eux; \
	docker-php-ext-enable opcache; \
	{ \
		echo 'opcache.memory_consumption=128'; \
		echo 'opcache.interned_strings_buffer=8'; \
		echo 'opcache.max_accelerated_files=4000'; \
		echo 'opcache.revalidate_freq=2'; \
		echo 'opcache.fast_shutdown=1'; \
	} > /usr/local/etc/php/conf.d/opcache-recommended.ini
# https://wordpress.org/support/article/editing-wp-config-php/#configure-error-logging
RUN { \
# https://www.php.net/manual/en/errorfunc.constants.php
# https://github.com/docker-library/wordpress/issues/420#issuecomment-517839670
		echo 'error_reporting = E_ERROR | E_WARNING | E_PARSE | E_CORE_ERROR | E_CORE_WARNING | E_COMPILE_ERROR | E_COMPILE_WARNING | E_RECOVERABLE_ERROR'; \
		echo 'display_errors = Off'; \
		echo 'display_startup_errors = Off'; \
		echo 'log_errors = On'; \
		echo 'error_log = /dev/stderr'; \
		echo 'log_errors_max_len = 1024'; \
		echo 'ignore_repeated_errors = On'; \
		echo 'ignore_repeated_source = Off'; \
		echo 'html_errors = Off'; \
	} > /usr/local/etc/php/conf.d/error-logging.ini

RUN set -eux; \
	a2enmod rewrite expires; \
	\
# https://httpd.apache.org/docs/2.4/mod/mod_remoteip.html
	a2enmod remoteip; \
	{ \
		echo 'RemoteIPHeader X-Forwarded-For'; \
# these IP ranges are reserved for "private" use and should thus *usually* be safe inside Docker
		echo 'RemoteIPTrustedProxy 10.0.0.0/8'; \
		echo 'RemoteIPTrustedProxy 172.16.0.0/12'; \
		echo 'RemoteIPTrustedProxy 192.168.0.0/16'; \
		echo 'RemoteIPTrustedProxy 169.254.0.0/16'; \
		echo 'RemoteIPTrustedProxy 127.0.0.0/8'; \
	} > /etc/apache2/conf-available/remoteip.conf; \
	a2enconf remoteip; \
# https://github.com/docker-library/wordpress/issues/383#issuecomment-507886512
# (replace all instances of "%h" with "%a" in LogFormat)
	find /etc/apache2 -type f -name '*.conf' -exec sed -ri 's/([[:space:]]*LogFormat[[:space:]]+"[^"]*)%h([^"]*")/\1%a\2/g' '{}' +


ENV WORDPRESS_VERSION 5.6
ENV WORDPRESS_SHA1 db8b75bfc9de27490434b365c12fd805ca6784ce

RUN set -ex; \
	curl -o wordpress.tar.gz -fSL "https://wordpress.org/wordpress-${WORDPRESS_VERSION}.tar.gz"; \
	echo "$WORDPRESS_SHA1 *wordpress.tar.gz" | sha1sum -c -; \
# upstream tarballs include ./wordpress/ so this gives us /usr/src/wordpress
	tar -xzf wordpress.tar.gz -C /usr/src/; \
	rm wordpress.tar.gz; \
	chown -R www-data:www-data /usr/src/wordpress; \
# pre-create wp-content (and single-level children) for folks who want to bind-mount themes, etc so permissions are pre-created properly instead of root:root
# wp-content/cache: https://github.com/docker-library/wordpress/issues/534#issuecomment-705733507
	mkdir wp-content; \
	for dir in /usr/src/wordpress/wp-content/*/ cache; do \
		dir="$(basename "${dir%/}")"; \
		mkdir "wp-content/$dir"; \
	done; \
	chown -R www-data:www-data wp-content; \
	chmod -R 777 wp-content

VOLUME /var/www/html

COPY docker-entrypoint.sh /usr/local/bin/

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["apache2-foreground"]

```

**Comment by XedinUnknown** [comment]
Hi! Any updates on this? What seems to be the blocker at the moment?

**Comment by XedinUnknown** [comment]
Why is my comment considered spam? I wanted to know what the problem is right now, how it could be possible to go around it, and what I can maybe do to help speed this up.

**Comment by shogo82148** [comment]
becoming a sponsor of https://github.com/sponsors/Danack who maintains imagick is the best way.

> https://github.com/Imagick/imagick/issues/358#issuecomment-742236891
>
> Please can you tell whoever runs your company that the Github sponsors program is now available for companies. If companies depend on software, then it needs to be supported or it will either go away, or be absorbed by Microsoft who appear to be borging as much of the software ecosystem as they can.
> https://github.com/sponsors/Danack

**Comment by LeoColomb** [comment]
@XedinUnknown I guess your comment is considered as spam as you ask a question answered literally 4 comments above. To be a real perfectionist developer, I'm sure the awakening would be appreciated.

**Comment by XedinUnknown** [comment]
@LeoColomb, that was over a month ago. Was just asking for an update, that's all.

**Comment by tianon** [comment]
Yes, this is still blocked on https://github.com/Imagick/imagick/issues/358 -- given the upstream developer's position, we're not going to override them and publish a build from master against their wishes.

Other questions it would be useful to figure out an answer to which could potentially unblock this:

> Possibility silly question. But WordPress supports both Imagick and GD out of the box. Would it be possible for to use GD instead of Imagick?

> Great question! Are _all_ the core functionality uses of `imagick` able to fall back to GD? What are the pros/cons? Is there one which is "officially" recommended/preferred over the other?

**Comment by TimothyBJacobs** [comment]
`imagick` is the preferred library, but GD is acceptable. https://make.wordpress.org/hosting/handbook/handbook/server-environment/#php-extensions. AFAIK the only major limitation in terms of feature sets is that Core can't generate PDF thumbnails with GD.

IMO it'd be worth it to generate the image with GD support. Particularly to make it easier for developers to test even if not all features are available.

**Comment by tianon** [comment]
That's exactly the type of documentation I was looking for; thank you @TimothyBJacobs! :heart:

From my reading of that, it sounds pretty strongly discouraged, but "good enough" to get folks testing PHP 8.0 (and we'll just have to wait for https://github.com/Imagick/imagick/issues/358 before it can be even considered as the default).

**Pull request merged**
