### PR TITLE
Add wordpress:fpm variant based on php:fpm base

### LINKED ISSUE #60: Nginx + PHP-FPM
It would make sense to move this to running on Nginx + PHP-FPM as not only would it be faster, scale better but also result in a smaller Docker image.

### PR DESCRIPTION
**Pull request by md5**
Fixes #60

### CODE REVIEW

**Comment by md5** [comment]
FYI, I originally opened this PR using a squashed version of this branch, but I decided that was silly to do preemptively and I force pushed the branch to unsquash the commits.

**Comment by yosifkit** [comment]
This seems fine to me; though I think we might want to change that `rsync` line to `tar` in the apache version too (then we can dump the rsync install as well).  What do you think @tianon?

Here is the pretty diff between the old and new versions:
```diff
diff --git a/apache/Dockerfile b/fpm/Dockerfile
index 798e997..084d06f 100644
--- a/apache/Dockerfile
+++ b/fpm/Dockerfile
@@ -1,12 +1,8 @@
-FROM php:5.6-apache
-
-RUN apt-get update && apt-get install -y rsync && rm -r /var/lib/apt/lists/*
-
-RUN a2enmod rewrite
+FROM php:5.6-fpm
 
 # install the PHP extensions we need
 RUN apt-get update && apt-get install -y libpng12-dev libjpeg-dev && rm -rf /var/lib/apt/lists/* \
- 	&& docker-php-ext-configure gd --with-png-dir=/usr --with-jpeg-dir=/usr \
+	&& docker-php-ext-configure gd --with-png-dir=/usr --with-jpeg-dir=/usr \
 	&& docker-php-ext-install gd
 RUN docker-php-ext-install mysqli
 
@@ -26,4 +22,4 @@ COPY docker-entrypoint.sh /entrypoint.sh
 
 # grr, ENTRYPOINT resets CMD now
 ENTRYPOINT ["/entrypoint.sh"]
-CMD ["apache2-foreground"]
+CMD ["php-fpm"]
diff --git a/apache/docker-entrypoint.sh b/fpm/docker-entrypoint.sh
index c34a8df..4bf8805 100755
--- a/apache/docker-entrypoint.sh
+++ b/fpm/docker-entrypoint.sh
@@ -40,18 +40,8 @@ if ! [ -e index.php -a -e wp-includes/version.php ]; then
 		echo >&2 "WARNING: $(pwd) is not empty - press Ctrl+C now if this is an error!"
 		( set -x; ls -A; sleep 10 )
 	fi
-	rsync --archive --one-file-system --quiet /usr/src/wordpress/ ./
+	tar cf - --one-file-system -C /usr/src/wordpress . | tar xf -
 	echo >&2 "Complete! WordPress has been successfully copied to $(pwd)"
-	if [ ! -e .htaccess ]; then
-		cat > .htaccess <<-'EOF'
-			RewriteEngine On
-			RewriteBase /
-			RewriteRule ^index\.php$ - [L]
-			RewriteCond %{REQUEST_FILENAME} !-f
-			RewriteCond %{REQUEST_FILENAME} !-d
-			RewriteRule . /index.php [L]
-		EOF
-	fi
 fi
 
 # TODO handle WordPress upgrades magically in the same way, but only if wp-includes/version.php's $wp_version is less than /usr/src/wordpress/wp-includes/version.php's $wp_version
```

**Comment by md5** [comment]
I agree about the switch from `rsync` to `tar` in the Apache entrypoint.sh. It might be nice also to share the entrypoint code somehow or even use the same script with some conditionals perhaps.

Would you like me to make the `rsync` to `tar` change?

**Comment by yosifkit** [comment]
I'll let @tianon give the final say on the rsync change when he gets back on the ground, but as far as I know, it is fine.

I am +1 on finding a way to make the entrypoint files the same.  Would it hurt to have an `htaccess` on the fpm version?.

**Comment by md5** [comment]
I wouldn't want to do anything while @tianon's off the ground :balloon: 

Regarding having the `.htaccess` in the FPM version, the only risk of having it there that I can see would be that it could mislead someone who sees it there and expects it to do something. I'm -1 for that reason.

**Comment by tianon** [comment]
I'm actually +1 on generating the `.htaccess` file in all cases, specifically because one of my favorite ways to use this image (and I'd imagine the same is probably true for others too) is to just bind-mount/`COPY` an existing Wordpress installation into it.  If we have both tags generate the same output/structure, it's possible for people to switch between them without any friction, and as a nice side benefit cuts down on the delta between them.

**Comment by tianon** [comment]
For example, switching from Apache to FPM could then be accomplished by stopping your Apache container, doing `--volumes-from` on a new FPM version, and then deleting the original.

**Comment by md5** [comment]
OK, you've sold me.

How about the `tar` v. `rsync` thing?

**Comment by tianon** [comment]
I'm +1 on `tar` instead, since it means we don't need an extra package installed (as long as the end result is the same -- I'm very familiar with the semantics of how `rsync` behaves in this situation, but not nearly as familiar with how `tar` behaves here)

**Comment by md5** [comment]
The main difference I could think of between using `tar` and `rsync` here would be if `index.php` and `wp-includes/version.php` didn't exist, but a bunch of the other files did. In that case, `tar` would unconditionally overwrite them while `rsync` would try to do something smart with them. I believe the end result in terms of permissions, ownership, and bits on disk would be identical.

Things start to differ if you include `--delete` in your `rsync`, but we don't have that here for obvious reasons.

I've made the updates to sync the entrypoint and remove rsync from the Apache `Dockerfile`.

**Comment by yosifkit** [comment]
Is there a reason for keeping a `docker-entrypoint.sh` in the root?

Other than my minor comment, LGTM

**Comment by md5** [comment]
@yosifkit I just put it there to have `update.sh` have a place to copy it from for the two copies.

**Comment by md5** [comment]
I think a better way to deal with this situation might be to start taking advantage of named Dockerfiles in Docker 1.5. Do you guys have any plans to support named Dockerfiles for official images?

**Comment by yosifkit** [comment]
I was just thinking about the library files supporting that, but no plans yet.

**Comment by md5** [comment]
ping @tianon

**Comment by tianon** [comment]
Merged by hand since I caused some conflicts for you. :+1:

**Comment by md5** [comment]
Thanks! Appreciate not having to rebase :metal: 

All this talk about running services as `root` made me realize today that the introduction of `wordpress:fpm` would mean a wordpress instance running as `root`... Hence docker-library/php#70

**Pull request merged**
