### PR TITLE
Fix problem with patching wp-config.php

### PR DESCRIPTION
**Pull request by mhueck**
The wp-config.php seems to have trailing spaces on some
lines. I have modified the RE to also match this.

This should fix the problem that people are reporting
for a few days.

### CODE REVIEW

**Comment by lazyfrosch** [comment]
Please see #117

**Comment by mhueck** [comment]
ok, you are right, the character which was causing the problem was a \r and not a space (both are covered in the \s which I used).
I am going to close this in favor of the other commit but maybe the regular expression should be a little more relaxed.

**Comment by zxkane** [comment]
I just pulled the latest image(built 3 days ago). I still see the same problem to connect the DB, which is an existing DB not a Mysql docker.

Are you sure the fix #117 resolved the problem?

**Comment by lazyfrosch** [comment]
@zxkane update to docker hub is still pending

**Pull request closed without merging**
