### PR TITLE
remove --path argument so plugins are loaded

### PR DESCRIPTION
**Pull request by terencehonles**
Remove `--path=/dev/null` so if the current directory is a wordpress directory it will load the plugins and correctly prefix "wp" when needed. The second if is changed to elif because the conditions are exclusive and if the first test matched the second doesn't need to run.

### CODE REVIEW

**Comment by tianon** [comment]
Does this mean to imply that WordPress plugins can also provide additional WP-CLI behavior?  Are there any documentation links on that you can share? (My searching isn't coming up with anything useful except the `wp plugin` subcommand, which is good but not related. :sweat_smile:)

**Comment by terencehonles** [comment]
I found a reference here: https://wp-cli.org/#extending and also here https://make.wordpress.org/cli/handbook/internal-api/wp-cli-add-command/ but I came across this when trying to install the ilabs mediacloud wordpress plugin.

Not that you're probably looking for this, but here's the code that it triggers https://github.com/Interfacelab/ilab-media-tools/blob/eb3ad995724d5c6355a9016870257eb80c20d91f/classes/CLI/Storage/StorageCommands.php#L161 and it is registered here https://github.com/Interfacelab/ilab-media-tools/blob/eb3ad995724d5c6355a9016870257eb80c20d91f/ilab-media-tools.php#L113

TBH: I'm not super familiar with wordpress and am still putting things together.

**Comment by terencehonles** [comment]
ping :)

**Comment by tianon** [comment]
Man, sorry for the delay. :bow:

I really appreciate the patience and the excellent links. :heart:

My concern with removing this is that we added for a reason, but I can't recall what that reason was (I'm sure there was some specific use case that broke without it).  Do you have any ideas?

Does `wp help foo` possibly fail if WordPress is not installed?

**Comment by terencehonles** [comment]
No worries, I think I package my own docker image which includes this, but I actually haven't used the cli _that_ much. I'm really not too familiar with wordpress. However this is what I'm thinking:

1. If wordpress isn't installed `wp` itself will fail (so the value of `--path` doesn't matter) and the container will try to execute the command as given.
2. If wordpress is installed `wp` will run and `help` will try to lookup a command that has been registered (via the core commands or plugins via `WP_CLI::add_command(...)`).

If help itself fails it would be because something has broken the CLI from loading. I'm not sure how defensive the CLI is but the `--path` argument looks like it affects this code: https://github.com/wp-cli/wp-cli/blob/d2a002214df900bba7303310f42c68b996d873ab/php/WP_CLI/Runner.php#L199-L233 which looks like it goes looking for `wp-load.php` or `index.php` up the FS. I'm guessing this was written this way to just try to be as fast as possible, but that's the limit to what I can suggest.

**Comment by yosifkit** [comment]
Rebased and coalesced the two `if` statements to one since they were doing the same thing.

LGTM cc @tianon

**Review by tianon — APPROVED** [review]

**Comment by terencehonles** [comment]
Thanks all! I look forward to updating my container and not having to mount over the entrypoint / reducing the extra config :sweat_smile:

**Pull request merged**
