### PR TITLE
Warn if both WORDPRESS_DB_HOST and MYSQL_PORT_3306_TCP are set

### PR DESCRIPTION
**Pull request by md5**

### CODE REVIEW

**Comment by mrjackdavis** [comment]
LGTM, I feel this is getting a bit messy though

**Comment by md5** [comment]
I'm curious how you think it's getting messy.

The only messy part in my opinion is that some people had been relying on the undocumented ability to set `MYSQL_PORT_3306_TCP` to configure an external database for this image. Since that ability was not a supported feature, I think @tianon's change in 9aae24350b9c4ede3d5db9cdac1ba88c3202fe98 was reasonable.

Now that the ability to configure an external db directly with `WORDPRESS_DB_HOST`, the situation seems pretty clean to me:

* If you want a linked database, use `--link mysql` and the `mysql` entry in `/etc/hosts` with be used as `DB_HOST` in `wp-config.php`
* If you want to use an external database, set `WORDPRESS_DB_HOST` and that value will be used directly for `DB_HOST` in `wp-config.php`

Once this PR is merged (or something like it), the user will be warned if they try to use both `-e WORDPRESS_DB_HOST=...` and `--link some-mysql:mysql`. If someone had been using `MYSQL_PORT_3306_TCP` directly and are now wondering why Wordpress isn't trying to connect to their external db, at least those people will also get an error message now.

**Comment by mrjackdavis** [comment]
Sorry @md5, I should've provided a bit more detail.

The reason I feel it's getting messy (100% subjective), is that a good amount of fringe case checks are entering the `docker-entrypoint.sh`; making it a little hard to read. It's fine for now. But IMHO if we continue on the current track it'll get a little unmanageable.

Otherwise, the fix is great. Thanks for doing that

**Comment by tianon** [comment]
LGTM

**Comment by tianon** [comment]
cc @yosifkit

**Comment by yosifkit** [comment]
LGTM

**Pull request merged**
