### PR TITLE
Add explicit "cli" variants for wp-cli

### PR DESCRIPTION
**Pull request by tianon**
See also:

- https://make.wordpress.org/core/2016/12/28/supporting-the-future-of-wp-cli/
- https://make.wordpress.org/cli/2017/01/03/lets-do-this/

The expected usage for these images is something like the following:

    docker run -it --rm \
        --volumes-from some-wordpress \
        --network container:some-wordpress \
        wordpress:cli user list

Closes #176

### CODE REVIEW

**Comment by tianon** [comment]
Rebased and updated to 1.1.0.

**Comment by tianon** [comment]
Full list of tags this adds:
```
cli-1.1.0
cli-1.1
cli-1
cli
php5.6-cli-1.1.0
php5.6-cli-1.1
php5.6-cli-1
php5.6-cli
php7.0-cli-1.1.0
php7.0-cli-1.1
php7.0-cli-1
php7.0-cli
php7.1-cli-1.1.0
php7.1-cli-1.1
php7.1-cli-1
php7.1-cli
```

**Comment by yosifkit** [comment]
I think these tags might be confused to be just `php:cli` and not `wp cli`. Maybe this is more clear?
```
cli-1.1.0-php5.6
```

**Comment by tianon** [comment]
Fair enough!  Updated list:
```
cli-1.1.0
cli-1.1
cli-1
cli
cli-1.1.0-php5.6
cli-1.1-php5.6
cli-1-php5.6
cli-php5.6
cli-1.1.0-php7.0
cli-1.1-php7.0
cli-1-php7.0
cli-php7.0
cli-1.1.0-php7.1
cli-1.1-php7.1
cli-1-php7.1
cli-php7.1
```

**Pull request merged**
