### PR TITLE
Add before-start-server script execution

### LINKED ISSUE #147: Hook in to specific point in  entrypoint script
I need to do some other stuff in the container **before** the `php-fpm` is started, but **after** `entrypoint.sh` file provisions wordpress.
In between those two steps, I want to add some plugins (via wp-cli).
So it would be nice if we could **hook** in to the setup process.

Just before `exec "$@"` we could have code that checks if there is a script in predetermined location, 
and if there is,  it executes it.

### PR DESCRIPTION
**Pull request by luiscoms**
It should fix #147 

In your `Dockerfile` just add your script

```Dockerfile
COPY before-start-server.sh /usr/local/bin/
```

### CODE REVIEW

**Comment by tianon** [comment]
Have you looked at using #142 for what you need?

**Comment by luiscoms** [comment]
No, in my case, I install cron inside container and I need to start it before start server

**Comment by tianon** [comment]
I'd really recommend trying to run `crond` in a separate container (using `--volumes-from` or similar to share the WordPress volume), but you should be able to accomplish what you're trying to do already via a command which fires up `crond` in the background before running this image-provided entrypoint script.

**Comment by luiscoms** [comment]
It could be a good approach, but this MR is useful yet

**Comment by yosifkit** [comment]
Basically the same response as https://github.com/docker-library/mongo/pull/298#discussion_r213764438; just swap MongoDB related items to Apache/PHP and WordPress appropriate paths, files, or actions:

>This is unnecessary since you can already hook a script to run before the entrypoint by running it before the entrypoint:
> 
> ```Dockerfile
> COPY my-setup-script.sh /docker-entrypoint-extras.d/my-setup-script.sh
> # could also just be CMD if you want to put your mongod args into the file
> ENTRYPOINT ["/docker-entrypoint-extras.d/my-setup-script.sh"]
> CMD ["docker-entrypoint.sh", "--keyFile", "/path/to/keyfile"]
> ```
> 
> Contents of `my-setup-script.sh`:
> 
> ``` bash
> #!/usr/bin/env bash
> 
> # pre-mongod setup 
> chmod 400 /path/to/keyfile
> 
> # ie: docker-entrypoint.sh --keyFile /path/to/keyfile
> exec "$@"
> ```

From related issue https://github.com/docker-library/mysql/issues/312 (ie, running cron in same container as X).

> Be warned that if cron ever crashes there would be nothing in the container that would restart it. It would be better to use a second container that just runs cron, or the host cron that does a docker exec, or add a process supervisor like supervisord.

Other related issues: https://github.com/docker-library/php/issues/248, https://github.com/docker-library/php/issues/301, https://github.com/docker-library/php/issues/409, https://github.com/docker-library/owncloud/issues/49

**Pull request closed without merging**
