### PR TITLE
Allow users to set additional configuration options

### PR DESCRIPTION
**Pull request by drewwestphal**
These changes allow a user to set additional configuration options via environment variables. The CONFIG_OPTS array defines variables that can be set in this fashion. 

To support this feature set_config has been modified to allow users to set config options to true, false and numeric values with proper (no) escaping. I've also added blank_config and del_config functions to facilitate configuration option setting.

### CODE REVIEW

**Comment by bejnar** [comment]
Some feedback after using this container to setup a WordPress Multisite: I think it’s nice to be able to modify the WP configuration using environment variables via something like this pull request. This way one can use docker-compose.yml to configure WP, which has some advantages for portability and keeping track of changes within a project.

I see the point about keeping the configuration options to the minimum required by WordPress. On the other hand, since, for example, setting up multisite is a standard feature of WP, one could argue that being able to set that up would be one of those minimum required options.

**Comment by drewwestphal** [comment]
For the time being you can just mount your own config and put that in the
repo
Le Mon, Sep 28, 2015 à 09:51, Roman Bejnar <notifications@github.com> a
écrit :

**Comment by bejnar** [comment]
Thank you for the tip! that seems like it would be a good way for now. As I understand it, one can mount volumes but not individual files? Apologies as I'm not sure if this is a general docker question or if it could help someone with a similar issue when using this container.

**Comment by drewwestphal** [comment]
You can mount specific files.

You would want to mount your wp-config file over
/var/www/html/wp-content/wp-config.php

**Comment by zyrill** [comment]
I actually prefer being able to set everything via env vars instead of mounting config files into the image. That way, the configuration becomes even more unencumbered from OS specifics (e.g. on win you have to use absolute paths). I would very much like to see this implemented.

**Comment by vutran** [comment]
I am for this PR. There's a lot of more constants that WP uses that isn't available in the `wp-config-sample.php` so those should be exposed as env vars.

**Comment by davisshaver** [comment]
+1 to seeing some action on this. At this point the most future proof solution seems to be extending the image and copying in a custom `wp-config-sample.php`. It would be nice to get official support for some additional environment variables within the official image.

**Comment by lwille** [comment]
See #142 for a generic solution.

**Comment by yosifkit** [comment]
Closing old issue; The generic solution has been merged in #142.

**Pull request closed without merging**
