### PR TITLE
Toggle WP_DEBUG with ENV

### PR DESCRIPTION
**Pull request by mgor**
Add possibility to change boolean values in wp-config.php.

FIxes https://github.com/docker-library/wordpress/issues/101

### CODE REVIEW

**Comment by yosifkit** [comment]
LGTM, Thanks! :heart:

**Comment by tianon** [comment]
LGTM :+1:

**Comment by rossjcooper** [comment]
Is this actually documented anywhere as an option? The only place I found reference to `WORDPRESS_DEBUG` was by looking at this PR

**Comment by tianon** [comment]
Nope, going to track that over in the docs issue you filed: https://github.com/docker-library/docs/issues/1042 :+1: (Thanks!)

**Pull request merged**
