### PR TITLE
Move "wp-config-docker.php" to non-beta (5.7 GA)

### PR DESCRIPTION
**Pull request by tianon**
See #557 for details on this functionality. :+1:

(GitHub is showing the diff in a strange way, but the new `docker-entrypoint.sh` is literally `docker-entrypoint-ng.sh` renamed :facepalm:)

### CODE REVIEW

**Comment by tianon** [comment]
(This is the change we comitted to make in #557 that needs to be merged before we send https://github.com/docker-library/wordpress/commit/24c4469ed874fa463db6e51c7038021acc825afd downstream. :+1:)

**Comment by tianon** [comment]
Just to make sure the important bits / migration path for users are in more places they might look when things don't seem to be working the same way they used to, see https://github.com/docker-library/wordpress/pull/557#issuecomment-756453476:

> For users who are changing `WORDPRESS_*` variables and expecting our `docker-entrypoint.sh` to update them, the "migration" path is to remove your `wp-config.php` file and let the new entrypoint copy in the updated version, and everything will "just work" from then on.

**Comment by youknowriad** [comment]
Noting that this PR broken `@wordpress/env` or `wp-env`. We're still trying to understand it exactly here https://github.com/WordPress/gutenberg/issues/29752

**Comment by damnMeddlingKid** [comment]
@tianon This PR removes the code to create the database in the entrypoint, is that intended behaviour going forward ?. if so we should update the docs at https://hub.docker.com/_/wordpress?tab=tags

**Comment by tianon** [comment]
Yep, that was intentional -- see https://github.com/docker-library/docs/pull/1892, especially https://github.com/docker-library/docs/pull/1892#issuecomment-797790551:

> Creating the database should not have been the job of the WordPress container since that means the database user has more access than it needs to store WordPress data.
>
> Both the `mysql` and `mariadb` images have support for creating a database and user with limited access (as is done in the example WordPress [`stack.yml` here](https://github.com/docker-library/docs/blob/7c6cd1abe90d7bf91654aac2ea0a6a31ed85c5a5/wordpress/stack.yml))

**Pull request merged**
