### PR TITLE
Refactor set_config function so it can be used for $table_prefix also

### LINKED ISSUE #96: Allow table_prefix to be set via ENV variables
I would like to propose an enhancement to the official image. Currently, it is not possible to change the table_prefix via an ENV variable which makes it a bit harder to get an existing installation (depending on a non standard table prefix) working. It would be an easy change and I'm sure it would help certain setups greatly (including mine).

### PR DESCRIPTION
**Pull request by tianon**
Fixes #96

### CODE REVIEW

**Comment by yosifkit** [comment]
LGTM

/cc @peterkuiper

**Comment by peterkuiper** [comment]
Nice solution, thanks

**Comment by tianon** [comment]
@peterkuiper oh, good point!  If you'd like to prepare a PR, that'd be fantastic! :heart:

**Comment by tianon** [comment]
(or if you'd rather, even just writing some text to describe it would be helpful :+1:)

If you do make a PR, be sure it's to `content.md`, since `README.md` is generated. :+1:

**Comment by peterkuiper** [comment]
Sure, are there docs to help me get started to do a correct PR? Haven't done that before for a public project :)

**Comment by yosifkit** [comment]
@peterkuiper, Thanks! We try to keep it fairly simple, just add stuff to https://github.com/docker-library/docs/blob/master/wordpress/content.md and make a PR that travis passes :smile:. You can run `./markdownfmt.sh -d wordpress` to do the relevant test from the travis file.

**Comment by peterkuiper** [comment]
I hope I did it correctly and my explanation makes sense :)

**Pull request merged**
