### PR TITLE
Make wp-content/ and wp-config.php overwrite optional

### PR DESCRIPTION
**Pull request by drzraf**
So that
* `wp-content` is mountable, and even moutable read-only (#115, #6, #281)
* `wp-config.php` is mountable (#200, #231, #135, #8, #142, #147)

### CODE REVIEW

**Comment by drzraf** [comment]
See #115, #281 and #6

**Comment by james-woods** [comment]
Any update on this?

**Comment by cyrilchapon** [comment]
up

**Comment by tianon** [comment]
Sorry for the long delay :bow:

The majority of the desired functionality here has been accomplished without any explicit environment variable through a combination of https://github.com/docker-library/wordpress/pull/206, https://github.com/docker-library/wordpress/pull/351, and (much more recently) https://github.com/docker-library/wordpress/pull/507.

- https://github.com/docker-library/wordpress/pull/206: no touching of `wp-config.php` unless we have variables set that imply we should
- https://github.com/docker-library/wordpress/pull/351: `tar --no-overwrite-dir`
- https://github.com/docker-library/wordpress/pull/507: exclude copying of `wp-content` directories which already exist

That last one isn't *exactly* what's asked for here, but I think it's pretty reasonable: the test isn't at all deep (just a directory existence check), so if you don't want to actually have the default themes/plugins, you can just pre-create the relevant directories (empty) and copying them will be skipped.

**Pull request closed without merging**
