### PR TITLE
inlarge upload size, via htaccess rule

### PR DESCRIPTION
**Pull request by mkdizajn**

### CODE REVIEW

**Comment by yosifkit** [comment]
Related discussion: #10.  I think so far we have opted to move to documentation (which still needs to be done) rather than changing the limit, but there could be compelling reasons to change it.

**Comment by mkdizajn** [comment]
thanks @yosifkit 

I didn't know of issue #10 but saw peaple requesting it on hub so I thought to help 

(maybe docs could describe correct steps how to alter that setting after docker started?)

**Comment by darwingr** [comment]
I went ahead and added 2 of my solutions to the comments in issue #10.

**Comment by pierreozoux** [comment]
+1 for doc explaining how to do it! Could you update your PR please? If not, just delete it.

Thanks!

**Comment by tianon** [comment]
Closing in favor of #10 (and improved documentation).  Thanks!

**Pull request closed without merging**
