### PR TITLE
Add env variable to handle wordpress subdirectory

### PR DESCRIPTION
**Pull request by rougeth**
Allow to proper change wordpress subdirectory. When `$WORDPRESS_SUBDIRECTORY` is set, the wordpress files will be moved to the relative folder configured, e.g.

`$ WORDPRESS_SUBDIRECTORY=blog # or /blog`

All wordpress files will be at `/var/www/html/blog` and you can access it on http://localhost/blog.

Related to #131.

### CODE REVIEW

**Comment by pasali** [comment]
👍

**Comment by EricTousignant** [comment]
I would love to see that feature added to the official image.

I think it's a very good practice for developers using version control to have WordPress in a subdirectory (ex.: /wordpress) and have their custom /wp-content in the root folder for their themes and plugins.

**Comment by anirbanroydas** [comment]
Has there been any update on this?

**Comment by jeanlaurent** [comment]
This is not trivial to achieve, considering the relative complexity of the `docker-entrypoint.sh` and the various `VOLUME` in the `Dockerfile`.

So this feature is a good addition.

**Comment by cnasikas** [comment]
This feature would be great and mandatory in my opinion.

It would be useful to have the following structure:

```
admin
    ---- wp-admin
    ---- wp-content
    ---- wp-includes
    ---- etc
app
    ---- plugins
    ---- themes
    ---- index.php
index.php
wp-config.php
.htaccess
```

and inside wp-config.php

```
if (!defined('WP_SITEURL')) {
	define('WP_SITEURL', 'http://' . $_SERVER['SERVER_NAME'] . '/admin');
}
if (!defined('WP_HOME')) {
	define('WP_HOME',    'http://' . $_SERVER['SERVER_NAME'] . '');
}
if (!defined('WP_CONTENT_DIR')) {
	define('WP_CONTENT_DIR', dirname(__FILE__) . '/app');
}
if (!defined('WP_CONTENT_URL')) {
	define('WP_CONTENT_URL', 'http://' . $_SERVER['SERVER_NAME'] . '/app');
}
```

**Comment by rougeth** [comment]
@tianon is there anything I can do to have this PR merged?

**Comment by tianon** [comment]
Can't this trivially be accomplished already by simply using `--workdir` on the container?

**Pull request closed without merging**
