### PR TITLE
Add original comments to .htaccess

### PR DESCRIPTION
**Pull request by Purii**
Ensure the compatibility by adding the original comments. See http://codex.wordpress.org/htaccess

### CODE REVIEW

**Comment by md5** [comment]
It would have been nice if you had described the compatibility problems you faced or quoted the part of the page that discusses the "BEGIN WordPress" and "END WordPress" comments. As it was, I ended up looking around the source code to figure out what the issue might be.

It looks like the relevant code is [`save_mod_rewrite_rules`](https://developer.wordpress.org/reference/functions/save_mod_rewrite_rules/#source-code) and [`insert_with_markers`](https://developer.wordpress.org/reference/functions/insert_with_markers/). In my quick search of the code, it appears to be involved in turning on and off the permalinks feature and in updating the rewrite rules when a you install WordPress upgrade.

**Comment by Purii** [comment]
I haven't looked which functions use this comments, because it is the default behaviour of WordPress. I thought it is enough to reference to the WordPress codex.
Sure, it doesn't break anything. It is just to make sure, that it looks exactly like a manual WP-Installation, to ensure that it works with future versions. And exactly.. I became aware of this behaviour, after changing the permalinks option. :)

**Comment by md5** [comment]
> I haven't looked which functions use this comments, because it is the default behaviour of WordPress. I thought it is enough to reference to the WordPress codex.

That's fine, but that page in the WordPress codex doesn't say anything about those comments being required. It may imply that by include the comments in all the examples, but as far as I could tell WordPress doesn't actually document the `BEGIN WordPress`/`END WordPress` thing anywhere.

**Comment by yosifkit** [comment]
LGTM

**Comment by Purii** [comment]
After changing permalinks setting, the content is set twice. Sure, this doesn't matter since it's the same content. But it doesn't look nice and future-compatible. And yes, WP use this comments only in this functions. I'm sorry, but I don't understand the need to discuss the motives of WP to use this comments.   *(btw, the oldest occurrence I could find is in version 2.3, and there's no reason WHY - [misc.php](https://develop.svn.wordpress.org/tags/2.3/wp-admin/includes/misc.php). Let's say it's common law? :wink:)*
```
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]

# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

# END WordPress
```

**Comment by tianon** [comment]
Seems legit to me, especially given that the WordPress source reads these markers. :+1:

**Comment by tianon** [comment]
(despite it not being properly documented, it is all over the codex and the forums as an accepted "thing" WordPress does)

**Pull request merged**
